### ISSUE TITLE
[BUG] pom file is missing project description

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/custom-codecs#68]
### What is the bug?
The pom file under  /org/opensearch/opensearch-custom-codecs is missing project description. This lead to maven publication to fail.

```
Invalid POM: /org/opensearch/opensearch-custom-codecs/2.10.0.0/opensearch-custom-codecs-2.10.0.0.pom: Project description missing
```

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
Maven POM validations should go through

### What is your host/environment?
Linux x64

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
We fixed the problem by manually adding the description for 2.10.0. But need this to be fixed before next release.

**Comment by gaiksaya** [comment]
@reta @andrross  FYI ^^

**Comment by reta** [comment]
@gaiksaya could you share the link to the build / command being used? have troubles to reproduce it

**Comment by gaiksaya** [comment]
This was the culprit https://repo1.maven.org/maven2/org/opensearch/opensearch-custom-codecs/2.10.0.0/opensearch-custom-codecs-2.10.0.0.pom

You can run [build.sh](https://github.com/opensearch-project/custom-codecs/blob/main/scripts/build.sh) to see the generated artifacts.
