### ISSUE TITLE
[BUG] Artifacts of Custom Codecs on the maven repository

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/custom-codecs#83]
### What is the bug?
This is more of a question. I can see in the maven repository that we have an [artifact](https://mvnrepository.com/artifact/org.opensearch/opensearch-custom-codecs) for custom-codecs, but the last version is 2.10.0. Is there is a reason why the 2.11.0 version was not added? Is there any process that we follow currently so that artifacts are published alongside OpenSearch release.

### What is the expected behavior?
A version of custom-codecs being released alongside other OpenSearch version releases.

@reta @nknize @andrross

**Comment by reta** [comment]
@sarthakaggarwal97 the `custom-codecs` is external plugin now (see please https://github.com/opensearch-project/custom-codecs/) so there are no artifacts to publish except the plugin ZIP.

**Comment by andrross** [comment]
I think this is the link to the artifacts for the external plugin: https://mvnrepository.com/artifact/org.opensearch.plugin/opensearch-custom-codecs

**Comment by sarthakaggarwal97** [comment]
got it, thanks for the inputs @andrross @reta
