### ISSUE TITLE
[BUG] Upgrade custom implementation to use Lucene99Codec

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/custom-codecs#94]
OS 2.x branch recently upgraded to use Lucene 9.9.1

We need to evaluate if we require changes in custom-codecs as well to rely on the new codecs introduced.

e.g. 
https://github.com/opensearch-project/custom-codecs/blob/main/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java#L93C36-L93C49

**Comment by mgodwan** [comment]
@sarthakaggarwal97 Can you please check?

**Comment by sarthakaggarwal97** [comment]
Thanks @mgodwan for creating the issue. Will take a look.

**Comment by andrross** [comment]
#99 has been merged to 2.x. Next we need to forward-port that change to main.

**Comment by sarthakaggarwal97** [comment]
Closing this as the change is merged! thanks
